# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_s = QtWidgets.QLabel(self.centralwidget)
        self.label_s.setGeometry(QtCore.QRect(30, 10, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_s.setFont(font)
        self.label_s.setObjectName("label_s")
        self.label_f = QtWidgets.QLabel(self.centralwidget)
        self.label_f.setGeometry(QtCore.QRect(30, 80, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_f.setFont(font)
        self.label_f.setObjectName("label_f")
        self.label_t = QtWidgets.QLabel(self.centralwidget)
        self.label_t.setGeometry(QtCore.QRect(30, 160, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_t.setFont(font)
        self.label_t.setObjectName("label_t")
        self.b_back = QtWidgets.QPushButton(self.centralwidget)
        self.b_back.setGeometry(QtCore.QRect(30, 332, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.b_back.setFont(font)
        self.b_back.setObjectName("b_back")
        self.b_next = QtWidgets.QPushButton(self.centralwidget)
        self.b_next.setGeometry(QtCore.QRect(540, 330, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.b_next.setFont(font)
        self.b_next.setObjectName("b_next")
        self.label_pass = QtWidgets.QLabel(self.centralwidget)
        self.label_pass.setGeometry(QtCore.QRect(400, 10, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_pass.setFont(font)
        self.label_pass.setObjectName("label_pass")
        self.label_snils = QtWidgets.QLabel(self.centralwidget)
        self.label_snils.setGeometry(QtCore.QRect(400, 80, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_snils.setFont(font)
        self.label_snils.setObjectName("label_snils")
        self.label_vznos = QtWidgets.QLabel(self.centralwidget)
        self.label_vznos.setGeometry(QtCore.QRect(400, 160, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_vznos.setFont(font)
        self.label_vznos.setObjectName("label_vznos")

        self.label_city = QtWidgets.QLabel(self.centralwidget)
        self.label_city.setGeometry(QtCore.QRect(30, 240, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_city.setFont(font)
        self.label_city.setObjectName("label_city")

        self.edit_city = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_city.setGeometry(QtCore.QRect(30, 290, 251, 21))
        self.edit_city.setObjectName("edit_city")
        self.edit_last = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_last.setGeometry(QtCore.QRect(30, 60, 251, 21))
        self.edit_last.setObjectName("edit_last")
        self.edit_vznos = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_vznos.setGeometry(QtCore.QRect(400, 210, 251, 21))
        self.edit_vznos.setObjectName("edit_vznos")
        self.edit_first = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_first.setGeometry(QtCore.QRect(30, 130, 251, 21))
        self.edit_first.setObjectName("edit_first")
        self.edit_third = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_third.setGeometry(QtCore.QRect(30, 210, 251, 21))
        self.edit_third.setObjectName("edit_third")
        self.edit_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_pass.setGeometry(QtCore.QRect(400, 60, 251, 21))
        self.edit_pass.setObjectName("edit_pass")

        self.edit_snils = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_snils.setGeometry(QtCore.QRect(400, 130, 251, 21))
        self.edit_snils.setObjectName("edit_snils")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_s.setText(_translate("MainWindow", "Фамилия"))
        self.label_f.setText(_translate("MainWindow", "Имя"))
        self.label_t.setText(_translate("MainWindow", "Отчество"))
        self.b_back.setText(_translate("MainWindow", "Назад"))
        self.b_next.setText(_translate("MainWindow", "Подтвердить"))
        self.label_pass.setText(_translate("MainWindow", "Паспорт"))
        self.label_snils.setText(_translate("MainWindow", "Снилс"))
        self.label_city.setText(_translate("MainWindow", "Город"))
        self.label_vznos.setText(_translate("MainWindow", "Взнос"))
